[package]
name = "volar-verifier-iop-runtime"
version = "0.1.0"
edition = "2024"
license.workspace = true
description.workspace = true
repository.workspace = true

[dependencies]
volar-iop = { path = "../volar-iop" }
volar-spec = { path = "../../spec/volar-spec" }
volar-discipline = { workspace = true }
hybrid-array.workspace = true
cipher.workspace = true
