// @pinnedness: unpinned
// @stability: very-unstable
// @ai: assisted
//! `Vec` lint over the `volar-compiler` IR (plan:
//! `docs/fhe/vec-elimination-and-linter-plan.md`; rule: `AGENTS.md` Core
//! Design Rule 11).
//!
//! This is a pure analysis pass in the shape of
//! [`lowering::TypeContext::validate_impl`](crate::lowering): it walks an
//! [`IrModule`] and returns the list of violations; empty means clean. It
//! runs on **parsed** IR (spec program structure) and on weaver-emitted IR.
//! It is *not* run on lowered/autogenerated code, which legitimately uses
//! `Vec` (the dyn mirror, generated interpreters) — see the plan.
//!
//! # What counts as `Vec`
//!
//! | Kind | IR form |
//! |---|---|
//! | [`VecUseKind::VecType`] | `IrType::Vector` (parses/prints as `Vec<T>`) or `IrType::Struct { Custom("Vec"), .. }` in a signature, field, or binding type |
//! | [`VecUseKind::VecCollect`] | `IrExprKind::IterPipeline` with terminal `IterStep::Collect` / `CollectTyped` — materializes a `Vec` |
//! | [`VecUseKind::VecCtorPath`] | `IrExprKind::Path` resolving to `Vec::new` / `Vec::with_capacity` |
//!
//! The Rust parser rejects `vec![...]` in parsed function bodies outright,
//! so the macro never reaches the IR from source.
//!
//! # Exemptions
//!
//! An item (or its enclosing module, threaded as context by the caller) is
//! exempt iff it carries a doc comment of the exact form
//!
//! ```text
//! /// @volar-allow-vec: <category>: <one-line reason>
//! ```
//!
//! with `category` one of `runtime-boundary`, `eval-key-store`,
//! `host-interpreter`, `test-fixture` (matching AGENTS.md). Because
//! exemptions are doc comments — which the IR does not retain on functions —
//! the caller (parser / weaver) supplies the set of exempt item names when
//! invoking [`lint_module`]; [`parse_allow_vec`] extracts the category from
//! `syn` attributes at parse time (same mechanism as `@volar-native:`).

#[cfg(feature = "std")]
use std::{format, string::ToString, vec::Vec};
#[cfg(not(feature = "std"))]
use alloc::{format, string::ToString, vec::Vec};

use volar_compiler::ir::*;

/// The recognized exemption categories (AGENTS.md Core Design Rule 11).
pub const ALLOW_VEC_CATEGORIES: [&str; 4] = [
    "runtime-boundary",
    "eval-key-store",
    "host-interpreter",
    "test-fixture",
];

/// One violation.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct VecLintError {
    /// Dotted path to the offending item (e.g. `my_fn:param[0]`).
    pub path: String,
    pub kind: VecUseKind,
    /// Human-readable note (why this form counts as `Vec`).
    pub note: String,
}

/// The classification of a `Vec` occurrence.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum VecUseKind {
    /// `Vec<T>` (or `Struct{Custom("Vec")}`) in a type position.
    VecType,
    /// An iterator pipeline materialized into a `Vec`.
    VecCollect,
    /// A `Vec::new` / `Vec::with_capacity` constructor path.
    VecCtorPath,
}

/// Extract the `@volar-allow-vec:` category from `syn` attributes, if a
/// valid exemption is present. Returns `Some(category)` on a recognized
/// category, `None` otherwise (an unrecognized category is *not* an
/// exemption — it fails closed).
#[cfg(feature = "parsing")]
pub fn parse_allow_vec(attrs: &[syn::Attribute]) -> Option<&'static str> {
    for attr in attrs {
        if !attr.path().is_ident("doc") {
            continue;
        }
        let doc_text: String = match &attr.meta {
            syn::Meta::NameValue(nv) => {
                if let syn::Expr::Lit(syn::ExprLit {
                    lit: syn::Lit::Str(s),
                    ..
                }) = &nv.value
                {
                    s.value()
                } else {
                    continue;
                }
            }
            _ => continue,
        };
        let text = doc_text.trim();
        if let Some(rest) = text.strip_prefix("@volar-allow-vec:") {
            let rest = rest.trim();
            let category = rest.split(':').next().unwrap_or("").trim();
            return allow_vec_category(category);
        }
    }
    None
}

/// Extract the `@volar-allow-vec:` category from plain doc-comment strings
/// (the IR-independent form, for callers that already hold doc text).
pub fn allow_vec_category_in_docs<'a>(docs: impl IntoIterator<Item = &'a str>) -> Option<&'static str> {
    for doc in docs {
        let text = doc.trim();
        // Accept both `/// @volar-allow-vec: ...` (real doc comment) and
        // the already-stripped `@volar-allow-vec: ...` form.
        let text = text.strip_prefix("///").map(str::trim_start).unwrap_or(text);
        if let Some(rest) = text.strip_prefix("@volar-allow-vec:") {
            let rest = rest.trim();
            let category = rest.split(':').next().unwrap_or("").trim();
            return allow_vec_category(category);
        }
    }
    None
}

/// Recognize a category string, failing closed on unrecognized ones.
fn allow_vec_category(category: &str) -> Option<&'static str> {
    ALLOW_VEC_CATEGORIES
        .iter()
        .find(|c| **c == category)
        .copied()
}

/// Lint a whole module. `exempt` is the set of item names (functions,
/// structs, enums, consts, type aliases) carrying a valid
/// `@volar-allow-vec:` exemption, supplied by the caller from parse-time
/// attributes. Module-level exemptions are the caller's responsibility to
/// fold into `exempt`.
pub fn lint_module<F, P: Clone>(
    module: &IrModule<F, P>,
    exempt: &dyn Fn(&str) -> bool,
) -> Vec<VecLintError>
where
    F: LintItem<P>,
{
    let mut errors = Vec::new();
    for f in &module.functions {
        f.lint_item(exempt, &mut errors);
    }
    for s in &module.structs {
        if exempt(&s.kind.to_string()) {
            continue;
        }
        for (i, field) in s.fields.iter().enumerate() {
            lint_type(
                &field.ty,
                &format!("{}:field[{}]", s.kind, i),
                exempt,
                &mut errors,
            );
        }
    }
    for e in &module.enums {
        if exempt(&e.kind.to_string()) {
            continue;
        }
        for v in &e.variants {
            match &v.fields {
                IrEnumVariantData::Tuple(tys) => {
                    for (i, ty) in tys.iter().enumerate() {
                        lint_type(
                            ty,
                            &format!("{}::{}[{}]", e.kind, v.name, i),
                            exempt,
                            &mut errors,
                        );
                    }
                }
                IrEnumVariantData::Struct(fields) => {
                    for (i, f) in fields.iter().enumerate() {
                        lint_type(
                            &f.ty,
                            &format!("{}::{}:{}", e.kind, v.name, i),
                            exempt,
                            &mut errors,
                        );
                    }
                }
                IrEnumVariantData::Unit => {}
            }
        }
    }
    for c in &module.consts {
        if exempt(&c.name) {
            continue;
        }
        lint_type(&c.ty, &format!("const {}", c.name), exempt, &mut errors);
        lint_expr(&c.value, &format!("const {}", c.name), exempt, &mut errors);
    }
    for a in &module.type_aliases {
        if exempt(&a.name) {
            continue;
        }
        lint_type(&a.target, &format!("type {}", a.name), exempt, &mut errors);
    }
    errors
}

/// The item surface the linter needs from a module's function type `F`.
/// Implemented for [`IrFunction`]; blanket over any function-like item.
pub trait LintItem<P: Clone> {
    fn lint_item(&self, exempt: &dyn Fn(&str) -> bool, errors: &mut Vec<VecLintError>);
}

impl<P: Clone> LintItem<P> for IrFunction<P> {
    fn lint_item(&self, exempt: &dyn Fn(&str) -> bool, errors: &mut Vec<VecLintError>) {
        if exempt(&self.name) {
            return;
        }
        for (i, p) in self.params.iter().enumerate() {
            lint_type(&p.ty, &format!("{}:param[{}]", self.name, i), exempt, errors);
        }
        if let Some(rt) = &self.return_type {
            lint_type(rt, &format!("{}:return", self.name), exempt, errors);
        }
        lint_block(&self.body, &self.name, exempt, errors);
    }
}

fn lint_block<P: Clone>(
    block: &IrBlock<P>,
    path: &str,
    exempt: &dyn Fn(&str) -> bool,
    errors: &mut Vec<VecLintError>,
) {
    for (i, stmt) in block.stmts.iter().enumerate() {
        let spath = format!("{}:stmt[{}]", path, i);
        match &stmt.kind {
            IrStmtKind::Let { ty, init, .. } => {
                if let Some(ty) = ty {
                    lint_type(ty, &spath, exempt, errors);
                }
                if let Some(init) = init {
                    lint_expr(init, &spath, exempt, errors);
                }
            }
            IrStmtKind::Semi(e) | IrStmtKind::Expr(e) => lint_expr(e, &spath, exempt, errors),
            // Catch-all for future statement kinds (repo rule 4).
            _ => {}
        }
    }
    if let Some(e) = &block.expr {
        lint_expr(e, &format!("{}:tail", path), exempt, errors);
    }
}

/// Walk a type for `Vec` in type position.
fn lint_type(
    ty: &IrType,
    path: &str,
    _exempt: &dyn Fn(&str) -> bool,
    errors: &mut Vec<VecLintError>,
) {
    match ty {
        IrType::Vector { elem } => {
            errors.push(VecLintError {
                path: path.to_string(),
                kind: VecUseKind::VecType,
                note: "Vec<T> in type position; use [T; N] / a presized inline capacity".into(),
            });
            lint_type(elem, path, _exempt, errors);
        }
        IrType::Struct { kind, type_args } => {
            if matches!(kind, StructKind::Custom(name) if name == "Vec") {
                errors.push(VecLintError {
                    path: path.to_string(),
                    kind: VecUseKind::VecType,
                    note: "Struct{Custom(\"Vec\")} in type position".into(),
                });
            }
            for a in type_args {
                lint_type(a, path, _exempt, errors);
            }
        }
        IrType::Array { elem, .. } | IrType::Reference { elem, .. } => {
            lint_type(elem, path, _exempt, errors)
        }
        IrType::Projection { base, .. } => lint_type(base, path, _exempt, errors),
        IrType::Existential { bounds, .. } => {
            for b in bounds {
                if let IrTraitBound { type_args, .. } = b {
                    for a in type_args {
                        lint_type(a, path, _exempt, errors);
                    }
                }
            }
        }
        IrType::FnPtr { params, ret, .. } => {
            for p in params {
                lint_type(p, path, _exempt, errors);
            }
            lint_type(ret, path, _exempt, errors);
        }
        _ => {}
    }
}

/// Walk an expression for `Vec` materialization/constructor forms.
fn lint_expr<P: Clone>(
    expr: &IrExpr<P>,
    path: &str,
    exempt: &dyn Fn(&str) -> bool,
    errors: &mut Vec<VecLintError>,
) {
    match &expr.kind {
        IrExprKind::Path { segments, type_args } => {
            let joined = segments.join("::");
            if joined == "Vec::new" || joined == "Vec::with_capacity" {
                errors.push(VecLintError {
                    path: path.to_string(),
                    kind: VecUseKind::VecCtorPath,
                    note: format!("`{}` allocates a Vec", joined),
                });
            }
            for a in type_args {
                lint_type(a, path, exempt, errors);
            }
        }
        IrExprKind::IterPipeline(chain) => {
            match &chain.terminal {
                IterTerminal::Collect => {
                    errors.push(VecLintError {
                        path: path.to_string(),
                        kind: VecUseKind::VecCollect,
                        note: "IterPipeline .collect() materializes a Vec; keep it lazy or presize".into(),
                    });
                }
                IterTerminal::CollectTyped(ty) => {
                    errors.push(VecLintError {
                        path: path.to_string(),
                        kind: VecUseKind::VecCollect,
                        note: "IterPipeline .collect::<T>() materializes a Vec".into(),
                    });
                    lint_type(ty, path, exempt, errors);
                }
                IterTerminal::Fold { init, body, .. } => {
                    lint_expr(init, path, exempt, errors);
                    lint_expr(body, path, exempt, errors);
                }
                IterTerminal::Lazy => {}
            }
            // Walk intermediate step bodies.
            for step in &chain.steps {
                match step {
                    IterStep::Map { body, .. }
                    | IterStep::Filter { body, .. }
                    | IterStep::FilterMap { body, .. }
                    | IterStep::FlatMap { body, .. } => lint_expr(body, path, exempt, errors),
                    _ => {}
                }
            }
            lint_iter_source(&chain.source, path, exempt, errors);
        }
        // Recurse through composite expressions.
        IrExprKind::Binary { left, right, .. } => {
            lint_expr(left, path, exempt, errors);
            lint_expr(right, path, exempt, errors);
        }
        IrExprKind::Unary { expr, .. } | IrExprKind::Cast { expr, .. } => {
            lint_expr(expr, path, exempt, errors)
        }
        IrExprKind::MethodCall { receiver, args, type_args, .. } => {
            lint_expr(receiver, path, exempt, errors);
            for a in args {
                lint_expr(a, path, exempt, errors);
            }
            for t in type_args {
                lint_type(t, path, exempt, errors);
            }
        }
        IrExprKind::Call { func, args } => {
            lint_expr(func, path, exempt, errors);
            for a in args {
                lint_expr(a, path, exempt, errors);
            }
        }
        IrExprKind::Field { base, .. } | IrExprKind::Index { base, .. } => {
            lint_expr(base, path, exempt, errors)
        }
        IrExprKind::StructExpr { fields, .. } => {
            for (_, e) in fields {
                lint_expr(e, path, exempt, errors);
            }
        }
        IrExprKind::Tuple(es) | IrExprKind::Array(es) | IrExprKind::FixedArray(es) => {
            for e in es {
                lint_expr(e, path, exempt, errors);
            }
        }
        IrExprKind::Repeat { elem, len } => {
            lint_expr(elem, path, exempt, errors);
            lint_expr(len, path, exempt, errors);
        }
        IrExprKind::ArrayGenerate { elem_ty, body, .. } => {
            if let Some(t) = elem_ty {
                lint_type(t, path, exempt, errors);
            }
            lint_expr(body, path, exempt, errors);
        }
        IrExprKind::Block(b) => lint_block(b, path, exempt, errors),
        IrExprKind::If { cond, then_branch, else_branch } => {
            lint_expr(cond, path, exempt, errors);
            lint_block(then_branch, path, exempt, errors);
            if let Some(e) = else_branch {
                lint_expr(e, path, exempt, errors);
            }
        }
        IrExprKind::Match { expr: scrutinee, arms } => {
            lint_expr(scrutinee, path, exempt, errors);
            for arm in arms {
                if let Some(g) = &arm.guard {
                    lint_expr(g, path, exempt, errors);
                }
                lint_expr(&arm.body, path, exempt, errors);
            }
        }
        IrExprKind::Closure { body, .. } => lint_expr(body, path, exempt, errors),
        IrExprKind::Return(e) | IrExprKind::Break(e) => {
            if let Some(e) = e {
                lint_expr(e, path, exempt, errors);
            }
        }
        IrExprKind::Assign { left, right } | IrExprKind::AssignOp { left, right, .. } => {
            lint_expr(left, path, exempt, errors);
            lint_expr(right, path, exempt, errors);
        }
        IrExprKind::Range { start, end, .. } => {
            if let Some(s) = start {
                lint_expr(s, path, exempt, errors);
            }
            if let Some(e) = end {
                lint_expr(e, path, exempt, errors);
            }
        }
        IrExprKind::WhileLoop { cond, body } => {
            lint_expr(cond, path, exempt, errors);
            lint_block(body, path, exempt, errors);
        }
        IrExprKind::BoundedLoop { body, .. } | IrExprKind::IterLoop { body, .. } => {
            lint_block(body, path, exempt, errors)
        }
        IrExprKind::RawMap { .. } | IrExprKind::RawZip { .. } | IrExprKind::RawFold { .. } => {
            // Raw forms carry closures/exprs in their own fields; linted
            // conservatively by their printers. Left as a no-op here.
        }
        _ => {}
    }
}

/// Walk an iterator chain's source for nested `Vec` forms.
fn lint_iter_source<P: Clone>(
    source: &IterChainSource<P>,
    path: &str,
    exempt: &dyn Fn(&str) -> bool,
    errors: &mut Vec<VecLintError>,
) {
    match source {
        IterChainSource::Method { collection, .. } => lint_expr(collection, path, exempt, errors),
        IterChainSource::Range { start, end, .. } => {
            lint_expr(start, path, exempt, errors);
            lint_expr(end, path, exempt, errors);
        }
        IterChainSource::Zip { left, right } => {
            lint_iter_source(&left.source, path, exempt, errors);
            lint_iter_source(&right.source, path, exempt, errors);
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn no_exempt(_: &str) -> bool {
        false
    }

    fn fn_with_param_ty(name: &str, ty: IrType) -> IrFunction {
        IrFunction {
            name: name.into(),
            module_path: vec![],
            generics: vec![],
            receiver: None,
            params: vec![IrParam { name: "x".into(), ty }],
            return_type: None,
            where_clause: vec![],
            body: IrBlock {
                stmts: vec![],
                expr: None,
            },
            external_kind: ExternalKind::Normal,
            no_inline: false,
        }
    }

    fn module_with(f: IrFunction) -> IrModule<IrFunction> {
        IrModule {
            name: "m".into(),
            functions: vec![f],
            structs: vec![],
            enums: vec![],
            traits: vec![],
            impls: vec![],
            type_aliases: vec![],
            consts: vec![],
        }
    }

    #[test]
    fn vector_type_is_flagged() {
        let f = fn_with_param_ty(
            "bad",
            IrType::Vector {
                elem: Box::new(IrType::Primitive(PrimitiveType::U32)),
            },
        );
        let errors = lint_module(&module_with(f), &no_exempt);
        assert_eq!(errors.len(), 1);
        assert_eq!(errors[0].kind, VecUseKind::VecType);
    }

    #[test]
    fn fixed_array_type_is_clean() {
        let f = fn_with_param_ty(
            "good",
            IrType::Array {
                kind: ArrayKind::FixedArray,
                elem: Box::new(IrType::Primitive(PrimitiveType::U32)),
                len: ArrayLength::Const(4),
            },
        );
        assert!(lint_module(&module_with(f), &no_exempt).is_empty());
    }

    #[test]
    fn exempt_function_is_skipped() {
        let f = fn_with_param_ty(
            "allowed",
            IrType::Vector {
                elem: Box::new(IrType::Primitive(PrimitiveType::U32)),
            },
        );
        let errors = lint_module(&module_with(f), &|name| name == "allowed");
        assert!(errors.is_empty());
    }

    #[test]
    fn collect_pipeline_is_flagged() {
        let mut f = fn_with_param_ty("collects", IrType::Primitive(PrimitiveType::U32));
        f.body.expr = Some(Box::new(IrExpr::new(
            IrExprKind::IterPipeline(IrIterChain {
                source: IterChainSource::Method {
                    collection: Box::new(IrExpr::new(IrExprKind::Var("xs".into()), (), None)),
                    method: IterMethod::Iter,
                },
                steps: vec![],
                terminal: IterTerminal::Collect,
            }),
            (),
            None,
        )));
        let errors = lint_module(&module_with(f), &no_exempt);
        assert!(errors.iter().any(|e| e.kind == VecUseKind::VecCollect));
    }

    #[test]
    fn vec_ctor_path_is_flagged() {
        let mut f = fn_with_param_ty("ctor", IrType::Primitive(PrimitiveType::U32));
        f.body.expr = Some(Box::new(IrExpr::new(
            IrExprKind::Path {
                segments: vec!["Vec".into(), "new".into()],
                type_args: vec![],
            },
            (),
            None,
        )));
        let errors = lint_module(&module_with(f), &no_exempt);
        assert!(errors.iter().any(|e| e.kind == VecUseKind::VecCtorPath));
    }

    #[test]
    fn allow_vec_category_parsing() {
        assert_eq!(
            allow_vec_category_in_docs(["/// @volar-allow-vec: eval-key-store: ~36 MB at Std128"]),
            Some("eval-key-store")
        );
        assert_eq!(
            allow_vec_category_in_docs(["@volar-allow-vec: runtime-boundary: x"]),
            Some("runtime-boundary")
        );
        // Unrecognized category fails closed.
        assert_eq!(
            allow_vec_category_in_docs(["@volar-allow-vec: whatever: x"]),
            None
        );
        assert_eq!(allow_vec_category_in_docs(["plain doc"]), None);
    }
}
