//! Dynamic (runtime-sized) versions of volar-spec types.
//!
//! This crate contains types where type-level length parameters (like `N: ArrayLength`)
//! have been converted to runtime `usize` witnesses stored as struct fields.
//! `GenericArray<T, N>` becomes `Vec<T>` with the length stored separately.
//!
//! The types in this crate are auto-generated by volar-compiler from volar-spec.

#![cfg_attr(not(feature = "std"), no_std)]
#![allow(
    unused_variables,
    dead_code,
    unused_mut,
    unused_imports,
    non_snake_case
)]

extern crate alloc;

// Re-export primitive field types - these stay the same
pub use volar_primitives::{Bit, BitsInBytes, BitsInBytes64, Galois, Galois64};

// Include the generated code
// This module is generated by running the volar-compiler test
#[cfg(feature = "generated")]
pub mod generated;

// Manual definitions as fallback / reference implementation
pub mod core_types;
