//! Text-level post-processing pass: chunk long, flat function bodies into
//! nested `{ let (a, b, ..) = { ...; (a, b, ..) }; }` blocks, so rustc's
//! AST name-resolution pass (`rustc_resolve::late`) never has to walk a
//! single scope ("rib") holding hundreds of flat `let` bindings.
//!
//! Profiling a real interpreter-scale woven module (`~2.1GB` printed
//! source, ~845 functions after `vole_split`'s own per-function
//! splitting) found `rustc` pinned in `rustc_resolve::late`'s
//! `resolve_path_with_ribs`/`record_segment_res` (a `HashMap` insert per
//! path segment), at 90GB+ resident memory on a 32GB machine, well
//! before MIR-borrowck or codegen ever started -- `vole_split.rs`'s own
//! `MAX_STMTS_PER_PIECE` splitting (which fixed the *per-function*
//! MIR-borrowck blowup) bounds function COUNT-adjacent cost, not this:
//! resolution cost is dominated by how many flat bindings share a
//! single scope, and a 500-statement piece still puts ~500 flat lets in
//! one rib. This pass re-chunks *within* an already-emitted function
//! body, at a much smaller granularity (tens, not hundreds).
//!
//! # Why text, not `IrExpr`/`IrStmt`
//!
//! A correct pass over the typed `IrExpr` tree would need a free-variable
//! walker over every `IrExprKind` variant (Call, MethodCall, Field,
//! Index, Binary, Block, ...) -- much larger and riskier than the win
//! justifies. Every printed woven function body is already mechanical,
//! effectively one statement per line, generated by this same pipeline's
//! own printer -- so this pass works on that printed text directly,
//! using a simple identifier-token search to decide which chunk-local
//! bindings need to cross a chunk boundary.
//!
//! # Why nested blocks need no input-threading (unlike `vole_split`)
//!
//! `vole_split::split_region_into_pieces` splits a region into separate
//! *functions*, which don't share scope, so it must thread values in
//! (`extra_in`, as call arguments) as well as out. A nested `{ }` block
//! stays inside the same function, so it sees every enclosing binding --
//! parameters, earlier `let`s, and earlier chunks' own exports -- for
//! free. Only *exporting* a chunk-local binding past its own block
//! needs anything at all: a trailing tuple expression, destructured by
//! the `let` that replaces the chunk.
//!
//! # Why every export is `.clone()`d, and every destructured name `mut`
//!
//! Determining a binding's true last use (to decide move-vs-clone, or
//! plain-vs-`mut`) would need the same cross-chunk analysis `vole_split`
//! already does, just re-derived at a finer, per-line granularity here.
//! Both choices are made conservatively instead: an export is always
//! `.clone()`d (an extra clone is wasted work, never a correctness
//! bug -- the moved-value bugs found and fixed elsewhere this session
//! all came from *missing* clones, never extra ones), and every
//! destructured name is declared `mut` regardless of whether it's ever
//! reassigned (`#![allow(unused_mut)]` is already part of every printed
//! module's own preamble -- see `print_weaved_vole_module` -- so this
//! costs nothing, not even a warning).

use alloc::collections::BTreeSet;
use alloc::format;
use alloc::string::{String, ToString};
use alloc::vec::Vec;

/// Chunk every `fn`/`pub fn` body found in `source` whose own top-level
/// statement count exceeds `chunk_size`, splitting it into a sequence of
/// nested blocks of at most `chunk_size` statements each. Bodies at or
/// under the threshold are returned byte-for-byte unchanged.
pub fn chunk_function_bodies(source: &str, chunk_size: usize) -> String {
    let mut out = String::with_capacity(source.len());
    let mut pos = 0usize;
    loop {
        let Some(fn_rel) = source[pos..].find("fn ") else {
            out.push_str(&source[pos..]);
            break;
        };
        let fn_abs = pos + fn_rel;
        let Some(brace_rel) = source[fn_abs..].find('{') else {
            out.push_str(&source[pos..]);
            break;
        };
        let body_open = fn_abs + brace_rel;
        out.push_str(&source[pos..=body_open]);
        let body_start = body_open + 1;
        let Some(close_rel) = find_matching_close(&source[body_start..]) else {
            // Malformed (shouldn't happen for real printer output) --
            // copy the rest verbatim rather than risk corrupting it.
            out.push_str(&source[body_start..]);
            pos = source.len();
            break;
        };
        let body_end = body_start + close_rel;
        out.push_str(&chunk_one_body(&source[body_start..body_end], chunk_size));
        out.push('}');
        pos = body_end + 1;
    }
    out
}

/// Byte offset of the `}` matching the implicit opening `{` at the start
/// of `s` (i.e. `s` is everything *after* that opening brace). Treats
/// `{`/`}`, `(`/`)`, and `[`/`]` uniformly as one combined depth counter
/// -- sufficient to correctly skip over array-repeat types (`[T; N]`,
/// which contain a `;` that is not a statement terminator) and any
/// nested struct-literal/closure `{ }` without needing a real Rust
/// tokenizer, since this pipeline's own generated code never contains
/// string/char literals whose contents could confuse a byte-level scan.
fn find_matching_close(s: &str) -> Option<usize> {
    let mut depth = 1i32;
    for (i, b) in s.bytes().enumerate() {
        match b {
            b'{' | b'(' | b'[' => depth += 1,
            b'}' | b')' | b']' => {
                depth -= 1;
                if depth == 0 {
                    return Some(i);
                }
            }
            _ => {}
        }
    }
    None
}

/// Split `body` (the text strictly between a function's own outer `{`
/// and `}`) into top-level statements (each still including its own
/// trailing `;`) and the trailing tail expression (no `;`, possibly
/// empty). A `;` only counts as a statement terminator at combined
/// bracket depth 0 -- see `find_matching_close`'s own doc for why.
fn split_top_level(body: &str) -> (Vec<&str>, &str) {
    let mut depth = 0i32;
    let mut stmt_start = 0usize;
    let mut stmts = Vec::new();
    for (i, b) in body.bytes().enumerate() {
        match b {
            b'{' | b'(' | b'[' => depth += 1,
            b'}' | b')' | b']' => depth -= 1,
            b';' if depth == 0 => {
                stmts.push(body[stmt_start..=i].trim());
                stmt_start = i + 1;
            }
            _ => {}
        }
    }
    (stmts, body[stmt_start..].trim())
}

/// Every distinct identifier-like token appearing anywhere in `text`
/// (keywords, type names, and method names included -- over-inclusive
/// on purpose, since this is only ever used to decide "might this name
/// still be needed," where a false positive costs one redundant clone
/// and a false negative would be a real bug).
fn extract_identifiers(text: &str) -> BTreeSet<String> {
    let mut out = BTreeSet::new();
    let bytes = text.as_bytes();
    let mut i = 0usize;
    while i < bytes.len() {
        if bytes[i].is_ascii_alphabetic() || bytes[i] == b'_' {
            let start = i;
            while i < bytes.len() && (bytes[i].is_ascii_alphanumeric() || bytes[i] == b'_') {
                i += 1;
            }
            out.insert(text[start..i].to_string());
        } else {
            i += 1;
        }
    }
    out
}

/// The name(s) a `let` statement binds, in left-to-right order, if
/// `stmt` (trimmed) starts with `let`. Handles a bare identifier
/// (`let x = ..;`, `let mut x: T = ..;`) or a tuple pattern
/// (`let (a, b) = ..;`, `let (mut a, b) = ..;`) -- the two shapes this
/// pipeline's own printer ever emits. Ignores `_`.
fn extract_let_bound_names(stmt: &str) -> Vec<String> {
    let trimmed = stmt.trim_start();
    let Some(mut rest) = trimmed.strip_prefix("let ") else {
        return Vec::new();
    };
    rest = rest.trim_start();
    if let Some(r) = rest.strip_prefix("mut ") {
        rest = r.trim_start();
    }
    let mut names = Vec::new();
    if let Some(inner_and_after) = rest.strip_prefix('(') {
        if let Some(close) = find_matching_close_paren(inner_and_after) {
            let inner = &inner_and_after[..close];
            for part in inner.split(',') {
                let mut p = part.trim();
                if let Some(pp) = p.strip_prefix("mut ") {
                    p = pp.trim();
                }
                let name: String = p.chars().take_while(|c| c.is_alphanumeric() || *c == '_').collect();
                if !name.is_empty() && name != "_" {
                    names.push(name);
                }
            }
        }
    } else {
        let name: String = rest.chars().take_while(|c| c.is_alphanumeric() || *c == '_').collect();
        if !name.is_empty() && name != "_" {
            names.push(name);
        }
    }
    names
}

/// Byte offset of the `)` matching an implicit opening `(` at the start
/// of `s`. Only used by `extract_let_bound_names` on a tuple pattern's
/// own (bracket-free, comma-separated identifier) contents, so a plain
/// depth counter over parens alone is enough.
fn find_matching_close_paren(s: &str) -> Option<usize> {
    let mut depth = 1i32;
    for (i, b) in s.bytes().enumerate() {
        match b {
            b'(' => depth += 1,
            b')' => {
                depth -= 1;
                if depth == 0 {
                    return Some(i);
                }
            }
            _ => {}
        }
    }
    None
}

/// Chunk one function's own body text (already unwrapped of its own
/// outer `{`/`}`) into nested blocks of at most `chunk_size` top-level
/// statements each. Returns the transformed body text (still without
/// its own outer `{`/`}` -- the caller re-adds those).
fn chunk_one_body(body: &str, chunk_size: usize) -> String {
    let (stmts, tail) = split_top_level(body);
    if stmts.len() <= chunk_size {
        return body.to_string();
    }

    let chunks: Vec<&[&str]> = stmts.chunks(chunk_size.max(1)).collect();
    let n = chunks.len();
    let mut used_after: BTreeSet<String> = extract_identifiers(tail);
    let mut rendered: Vec<String> = alloc::vec![String::new(); n];

    for idx in (0..n).rev() {
        let chunk = chunks[idx];

        let mut defined_order: Vec<String> = Vec::new();
        let mut defined_set: BTreeSet<String> = BTreeSet::new();
        for s in chunk {
            for name in extract_let_bound_names(s) {
                if defined_set.insert(name.clone()) {
                    defined_order.push(name);
                }
            }
        }
        let exports: Vec<String> = defined_order.into_iter().filter(|nm| used_after.contains(nm)).collect();

        let mut block = String::new();
        for s in chunk {
            block.push_str(s.trim());
            block.push('\n');
        }

        rendered[idx] = if exports.is_empty() {
            // Nothing crosses the boundary -- still isolate the chunk
            // into its own scope (bounding its rib) as a bare block
            // statement, no destructuring needed.
            format!("{{\n{block}}}\n")
        } else {
            let tuple_pat = exports.iter().map(|e| format!("mut {e}")).collect::<Vec<_>>().join(", ");
            let tuple_ret = exports.iter().map(|e| format!("{e}.clone()")).collect::<Vec<_>>().join(", ");
            if exports.len() == 1 {
                block.push_str(&tuple_ret);
                block.push('\n');
                format!("let {tuple_pat} = {{\n{block}}};\n")
            } else {
                block.push_str(&format!("({tuple_ret})\n"));
                format!("let ({tuple_pat}) = {{\n{block}}};\n")
            }
        };

        for s in chunk {
            used_after.extend(extract_identifiers(s));
        }
    }

    let mut out = String::with_capacity(body.len() + n * 32);
    for r in rendered {
        out.push_str(&r);
    }
    if !tail.is_empty() {
        out.push_str(tail);
        out.push('\n');
    }
    out
}

#[cfg(test)]
mod tests {
    extern crate std;
    use super::*;

    #[test]
    fn body_under_threshold_is_unchanged() {
        let src = "fn f() {\nlet a = 1;\nlet b = 2;\n(a, b)\n}\n";
        assert_eq!(chunk_function_bodies(src, 10), src);
    }

    #[test]
    fn body_over_threshold_gets_chunked_and_stays_balanced() {
        let mut body = String::new();
        for i in 0..10 {
            body += &format!("let v{i} = f(v{});\n", if i == 0 { 0 } else { i - 1 });
        }
        body += "(v9)\n";
        let src = format!("pub fn f() {{\n{body}}}\n");
        let out = chunk_function_bodies(&src, 3);
        assert_ne!(out, src, "an over-threshold body must actually be rewritten");
        // Every original binding name must still appear somewhere.
        for i in 0..10 {
            assert!(out.contains(&format!("v{i}")), "v{i} must survive chunking");
        }
        // Braces/parens must stay balanced (a crude but meaningful sanity
        // check that the rewrite didn't corrupt the structure).
        let mut depth = 0i32;
        for b in out.bytes() {
            match b {
                b'{' | b'(' | b'[' => depth += 1,
                b'}' | b')' | b']' => depth -= 1,
                _ => {}
            }
        }
        assert_eq!(depth, 0, "brackets must balance: {out}");
    }

    #[test]
    fn cross_chunk_reference_is_exported_and_reused() {
        // v0 is defined in the first chunk and used again in the last --
        // it must appear in some exported tuple, not just its own def.
        let src = "pub fn f() {\nlet v0 = a();\nlet v1 = b();\nlet v2 = c();\nlet v3 = d();\nlet v4 = e(v0);\n(v4)\n}\n";
        let out = chunk_function_bodies(src, 2);
        assert!(out.contains("v0.clone()"), "v0 must be exported via clone across the chunk boundary:\n{out}");
    }

    #[test]
    fn tuple_let_pattern_names_are_extracted() {
        let names = extract_let_bound_names("let (a, mut b, c) = f();");
        assert_eq!(names, alloc::vec!["a".to_string(), "b".to_string(), "c".to_string()]);
    }

    #[test]
    fn array_repeat_type_semicolon_is_not_a_statement_boundary() {
        let body = "let x: [u8; 5] = [0; 5];\nlet y = 1;\n(x, y)\n";
        let (stmts, tail) = split_top_level(body);
        assert_eq!(stmts.len(), 2, "the `;` inside `[u8; 5]`/`[0; 5]` must not split a statement: {stmts:?}");
        assert_eq!(tail, "(x, y)");
    }
}
