//! Text-level post-processing pass: chunk long, flat function bodies into
//! nested `{ let (a, b, ..) = { ...; (a, b, ..) }; }` blocks, so rustc's
//! AST name-resolution pass (`rustc_resolve::late`) never has to walk a
//! single scope ("rib") holding hundreds of flat `let` bindings.
//!
//! Profiling a real interpreter-scale woven module (`~2.1GB` printed
//! source, ~845 functions after `vole_split`'s own per-function
//! splitting) found `rustc` pinned in `rustc_resolve::late`'s
//! `resolve_path_with_ribs`/`record_segment_res` (a `HashMap` insert per
//! path segment), at 90GB+ resident memory on a 32GB machine, well
//! before MIR-borrowck or codegen ever started -- `vole_split.rs`'s own
//! `MAX_STMTS_PER_PIECE` splitting (which fixed the *per-function*
//! MIR-borrowck blowup) bounds function COUNT-adjacent cost, not this:
//! resolution cost is dominated by how many flat bindings share a
//! single scope, and a 500-statement piece still puts ~500 flat lets in
//! one rib. This pass re-chunks *within* an already-emitted function
//! body, at a much smaller granularity (tens, not hundreds).
//!
//! # Why text, not `IrExpr`/`IrStmt`
//!
//! A correct pass over the typed `IrExpr` tree would need a free-variable
//! walker over every `IrExprKind` variant (Call, MethodCall, Field,
//! Index, Binary, Block, ...) -- much larger and riskier than the win
//! justifies. Every printed woven function body is already mechanical,
//! effectively one statement per line, generated by this same pipeline's
//! own printer -- so this pass works on that printed text directly,
//! using a simple identifier-token search to decide which chunk-local
//! bindings need to cross a chunk boundary.
//!
//! # Why nested blocks need no input-threading (unlike `vole_split`)
//!
//! `vole_split::split_region_into_pieces` splits a region into separate
//! *functions*, which don't share scope, so it must thread values in
//! (`extra_in`, as call arguments) as well as out. A nested `{ }` block
//! stays inside the same function, so it sees every enclosing binding --
//! parameters, earlier `let`s, and earlier chunks' own exports -- for
//! free. Only *exporting* a chunk-local binding past its own block
//! needs anything at all: a trailing tuple expression, destructured by
//! the `let` that replaces the chunk.
//!
//! # Why every export is `.clone()`d, and every destructured name `mut`
//!
//! Determining a binding's true last use (to decide move-vs-clone, or
//! plain-vs-`mut`) would need the same cross-chunk analysis `vole_split`
//! already does, just re-derived at a finer, per-line granularity here.
//! Both choices are made conservatively instead: an export is always
//! `.clone()`d (an extra clone is wasted work, never a correctness
//! bug -- the moved-value bugs found and fixed elsewhere this session
//! all came from *missing* clones, never extra ones), and every
//! destructured name is declared `mut` regardless of whether it's ever
//! reassigned (`#![allow(unused_mut)]` is already part of every printed
//! module's own preamble -- see `print_weaved_vole_module` -- so this
//! costs nothing, not even a warning).

use alloc::collections::BTreeSet;
use alloc::format;
use alloc::string::{String, ToString};
use alloc::vec::Vec;

/// Chunk every `fn`/`pub fn` body found in `source` whose own top-level
/// statement count exceeds `chunk_size`, splitting it into a sequence of
/// nested blocks of at most `chunk_size` statements each. Bodies at or
/// under the threshold are returned byte-for-byte unchanged.
pub fn chunk_function_bodies(source: &str, chunk_size: usize) -> String {
    let mut out = String::with_capacity(source.len());
    let mut pos = 0usize;
    loop {
        let Some(fn_rel) = source[pos..].find("fn ") else {
            out.push_str(&source[pos..]);
            break;
        };
        let fn_abs = pos + fn_rel;
        let Some(brace_rel) = source[fn_abs..].find('{') else {
            out.push_str(&source[pos..]);
            break;
        };
        let body_open = fn_abs + brace_rel;
        out.push_str(&source[pos..=body_open]);
        let body_start = body_open + 1;
        let Some(close_rel) = find_matching_close(&source[body_start..]) else {
            // Malformed (shouldn't happen for real printer output) --
            // copy the rest verbatim rather than risk corrupting it.
            out.push_str(&source[body_start..]);
            pos = source.len();
            break;
        };
        let body_end = body_start + close_rel;
        out.push_str(&chunk_one_body(&source[body_start..body_end], chunk_size));
        out.push('}');
        pos = body_end + 1;
    }
    out
}

/// Byte offset of the `}` matching the implicit opening `{` at the start
/// of `s` (i.e. `s` is everything *after* that opening brace). Treats
/// `{`/`}`, `(`/`)`, and `[`/`]` uniformly as one combined depth counter
/// -- sufficient to correctly skip over array-repeat types (`[T; N]`,
/// which contain a `;` that is not a statement terminator) and any
/// nested struct-literal/closure `{ }` without needing a real Rust
/// tokenizer, since this pipeline's own generated code never contains
/// string/char literals whose contents could confuse a byte-level scan.
fn find_matching_close(s: &str) -> Option<usize> {
    let mut depth = 1i32;
    for (i, b) in s.bytes().enumerate() {
        match b {
            b'{' | b'(' | b'[' => depth += 1,
            b'}' | b')' | b']' => {
                depth -= 1;
                if depth == 0 {
                    return Some(i);
                }
            }
            _ => {}
        }
    }
    None
}

/// Split `body` (the text strictly between a function's own outer `{`
/// and `}`) into top-level statements (each still including its own
/// trailing `;`) and the trailing tail expression (no `;`, possibly
/// empty). A `;` only counts as a statement terminator at combined
/// bracket depth 0 -- see `find_matching_close`'s own doc for why.
fn split_top_level(body: &str) -> (Vec<&str>, &str) {
    let mut depth = 0i32;
    let mut stmt_start = 0usize;
    let mut stmts = Vec::new();
    for (i, b) in body.bytes().enumerate() {
        match b {
            b'{' | b'(' | b'[' => depth += 1,
            b'}' | b')' | b']' => depth -= 1,
            b';' if depth == 0 => {
                stmts.push(body[stmt_start..=i].trim());
                stmt_start = i + 1;
            }
            _ => {}
        }
    }
    (stmts, body[stmt_start..].trim())
}

/// Every distinct identifier-like token appearing anywhere in `text`
/// (keywords, type names, and method names included -- over-inclusive
/// on purpose, since this is only ever used to decide "might this name
/// still be needed," where a false positive costs one redundant clone
/// and a false negative would be a real bug).
fn extract_identifiers(text: &str) -> BTreeSet<String> {
    let mut out = BTreeSet::new();
    let bytes = text.as_bytes();
    let mut i = 0usize;
    while i < bytes.len() {
        if bytes[i].is_ascii_alphabetic() || bytes[i] == b'_' {
            let start = i;
            while i < bytes.len() && (bytes[i].is_ascii_alphanumeric() || bytes[i] == b'_') {
                i += 1;
            }
            out.insert(text[start..i].to_string());
        } else {
            i += 1;
        }
    }
    out
}

/// Byte offset of a `let` statement's own top-level assignment `=` (not
/// `==`/`!=`/`<=`/`>=`), if `stmt` (trimmed) starts with `let`. A `let`
/// statement's own LHS (`let PATTERN [: TYPE] =`) never itself contains
/// `=` (patterns/types don't have comparison operators), so the first
/// qualifying `=` found by a left-to-right scan is unambiguously the
/// assignment.
fn let_assignment_eq_pos(stmt: &str) -> Option<usize> {
    if !stmt.trim_start().starts_with("let ") {
        return None;
    }
    let bytes = stmt.as_bytes();
    for i in 0..bytes.len() {
        if bytes[i] != b'=' {
            continue;
        }
        let prev_cmp = i > 0 && matches!(bytes[i - 1], b'=' | b'!' | b'<' | b'>');
        let next_eq = i + 1 < bytes.len() && bytes[i + 1] == b'=';
        if !prev_cmp && !next_eq {
            return Some(i);
        }
    }
    None
}

/// Identifiers `stmt` *references* (reads), for the purpose of deciding
/// whether an earlier chunk's own binding needs to survive past this
/// statement -- unlike [`extract_identifiers`], a `let` statement's own
/// LHS names are excluded (a `let x = ..;` *shadows*/(re)defines `x`,
/// it doesn't reference whatever `x` meant before it, so counting it as
/// a "later use" of an earlier same-named binding is wrong -- this
/// matters once bindings can be reused/shadowed, e.g. pool-scratch
/// helpers that deliberately reuse a fixed temp name per call site).
fn extract_referenced_identifiers(stmt: &str) -> BTreeSet<String> {
    match let_assignment_eq_pos(stmt) {
        Some(eq) => extract_identifiers(&stmt[eq + 1..]),
        None => extract_identifiers(stmt),
    }
}

/// The name(s) a `let` statement binds, in left-to-right order, if
/// `stmt` (trimmed) starts with `let`. Handles a bare identifier
/// (`let x = ..;`, `let mut x: T = ..;`) or a tuple pattern
/// (`let (a, b) = ..;`, `let (mut a, b) = ..;`) -- the two shapes this
/// pipeline's own printer ever emits. Ignores `_`.
fn extract_let_bound_names(stmt: &str) -> Vec<String> {
    let trimmed = stmt.trim_start();
    let Some(mut rest) = trimmed.strip_prefix("let ") else {
        return Vec::new();
    };
    rest = rest.trim_start();
    if let Some(r) = rest.strip_prefix("mut ") {
        rest = r.trim_start();
    }
    let mut names = Vec::new();
    if let Some(inner_and_after) = rest.strip_prefix('(') {
        if let Some(close) = find_matching_close_paren(inner_and_after) {
            let inner = &inner_and_after[..close];
            for part in inner.split(',') {
                let mut p = part.trim();
                if let Some(pp) = p.strip_prefix("mut ") {
                    p = pp.trim();
                }
                let name: String = p.chars().take_while(|c| c.is_alphanumeric() || *c == '_').collect();
                if !name.is_empty() && name != "_" {
                    names.push(name);
                }
            }
        }
    } else {
        let name: String = rest.chars().take_while(|c| c.is_alphanumeric() || *c == '_').collect();
        if !name.is_empty() && name != "_" {
            names.push(name);
        }
    }
    names
}

/// Byte offset of the `)` matching an implicit opening `(` at the start
/// of `s`. Only used by `extract_let_bound_names` on a tuple pattern's
/// own (bracket-free, comma-separated identifier) contents, so a plain
/// depth counter over parens alone is enough.
fn find_matching_close_paren(s: &str) -> Option<usize> {
    let mut depth = 1i32;
    for (i, b) in s.bytes().enumerate() {
        match b {
            b'(' => depth += 1,
            b')' => {
                depth -= 1;
                if depth == 0 {
                    return Some(i);
                }
            }
            _ => {}
        }
    }
    None
}

/// For every name `let`-defined more than once anywhere in `stmts`
/// (this pipeline's own convention: a genuine, individually-meaningful
/// circuit value is *never* redefined under the same name within one
/// function -- only a deliberately reused/shadowed scratch temp is, e.g.
/// `vole.rs`'s pool-scratch helpers' `_and_wire`/`_and_qand`), find each
/// of its own "epochs" (from one `let` defining it up to, but not
/// including, the next `let` that redefines it, or the end of `stmts`)
/// and that epoch's own *last* referencing statement index within it.
/// Returns `(def_index, last_ref_index)` pairs -- a chunk boundary
/// strictly inside `(def_index, last_ref_index]` would split that
/// specific instance's own live range, since some statement at or before
/// `last_ref_index` still needs to read the value `def_index` bound.
///
/// Deliberately skips names defined only once: those are already handled
/// correctly by `chunk_one_body`'s own `used_after`-based export
/// mechanism, and computing this per-name epoch scan for every one of
/// them (typically hundreds per function) would be needless work -- only
/// the small set of genuinely reused names needs it.
fn reused_name_live_ranges(stmts: &[&str]) -> Vec<(usize, usize)> {
    let n = stmts.len();
    let mut def_count: alloc::collections::BTreeMap<String, usize> = alloc::collections::BTreeMap::new();
    for s in stmts {
        for nm in extract_let_bound_names(s) {
            *def_count.entry(nm).or_insert(0) += 1;
        }
    }
    let reused: BTreeSet<String> = def_count.into_iter().filter(|(_, c)| *c > 1).map(|(k, _)| k).collect();
    if reused.is_empty() {
        return Vec::new();
    }

    let mut ranges = Vec::new();
    for d in 0..n {
        let defined: BTreeSet<String> = extract_let_bound_names(stmts[d]).into_iter().filter(|nm| reused.contains(nm)).collect();
        if defined.is_empty() {
            continue;
        }
        let mut epoch_end = n;
        'outer: for j in (d + 1)..n {
            for nm in extract_let_bound_names(stmts[j]) {
                if defined.contains(&nm) {
                    epoch_end = j;
                    break 'outer;
                }
            }
        }
        let mut last_ref = d;
        for (j, s) in stmts.iter().enumerate().take(epoch_end).skip(d) {
            let refs = extract_referenced_identifiers(s);
            if defined.iter().any(|nm| refs.contains(nm)) {
                last_ref = j;
            }
        }
        if last_ref > d {
            ranges.push((d, last_ref));
        }
    }
    ranges
}

/// Every chunk-boundary end index (exclusive), roughly every
/// `chunk_size` statements, adjusted so no boundary ever falls inside a
/// reused/shadowed name's own live range (see
/// [`reused_name_live_ranges`]) -- e.g. `vole.rs`'s own pool-scratch
/// helpers' `let _and_qand = ..; let _and_wire = _and_qand.clone();
/// _pool.push(_and_qand); _pool.push(_and_wire);` shape, where
/// `_and_wire`'s own definition and its own use (the second `push`) are
/// *not* adjacent statements (an unrelated `_and_qand` push sits between
/// them). Without this, a boundary landing inside that range turns a
/// same-chunk self-reference into a cross-chunk one, which the "defined
/// more than once in one chunk -> never export" rule (needed for a
/// *different* reason -- see `chunk_one_body`'s own export-filtering
/// doc) can't safely resolve either way: exporting risks handing back an
/// already-consumed value, not exporting risks "cannot find value" if a
/// later chunk's own reference no longer sees it. Keeping a reused
/// name's own live range inside one chunk sidesteps the ambiguity
/// instead of trying to resolve it.
fn chunk_end_indices(stmts: &[&str], chunk_size: usize) -> Vec<usize> {
    let step = chunk_size.max(1);
    let mut ends = Vec::new();
    let mut next = step;
    while next < stmts.len() {
        ends.push(next);
        next += step;
    }

    let ranges = reused_name_live_ranges(stmts);
    if !ranges.is_empty() {
        for end in ends.iter_mut() {
            loop {
                if *end >= stmts.len() {
                    break;
                }
                // `*end` is a boundary strictly inside (d, last_ref] if
                // it lands anywhere in `d+1..=last_ref` -- shift past the
                // furthest-reaching such range covering it, then re-check
                // (the new position could itself fall inside another).
                let blocking = ranges.iter().filter(|&&(d, l)| *end > d && *end <= l).map(|&(_, l)| l).max();
                match blocking {
                    Some(l) => *end = l + 1,
                    None => break,
                }
            }
        }
    }

    // Defensive: keep boundaries non-decreasing even if an adjustment
    // above ever pushed one past the next "natural" boundary (not
    // expected at realistic chunk sizes, since each adjustment only
    // pulls in a handful of tightly-coupled statements, but cheap to
    // guarantee outright rather than assume).
    let mut prev_end = 0usize;
    for end in ends.iter_mut() {
        if *end < prev_end {
            *end = prev_end;
        }
        prev_end = *end;
    }
    ends
}

/// Recursively chunk any `core::array::from_fn(|i| { ... })` closure
/// body found anywhere in `text`, using the exact same algorithm as an
/// enclosing function body ([`chunk_one_body`] itself). Closures are
/// entirely opaque to [`split_top_level`]'s own top-level statement
/// split -- the whole closure, braces and all, is part of ONE top-level
/// statement from the enclosing body's point of view -- so without this,
/// a large closure body (a single wide, `>1`-bit `Poly` statement's own
/// AND-gate/XOR-chain scratch, potentially many statements) would never
/// get bounded at all, regardless of `chunk_size`: exactly the
/// unbounded-rib problem this whole pass exists to prevent, just
/// re-appearing one level down, unaddressed by the outer-body-only
/// chunking alone.
///
/// Detects closures via the literal text `"|i| {"` -- this weaver's ONLY
/// multi-statement closure body is `emit_poly_wide`'s own per-lane
/// closure (`crates/compiler/volar-weaver/src/vole.rs`'s
/// `fixed_array_from_fn("i", ..)`), always with parameter name `i`; the
/// handful of OTHER (`array_t_from_fn`) closures this weaver generates
/// are always a single expression, never exceed `chunk_size`, and this
/// is a harmless no-op on them regardless. `|` never otherwise appears
/// in this pipeline's own generated code (no bitwise-or, no `|`-pattern
/// matching in this DSL), so the match is unambiguous.
fn chunk_closures_in_text(text: &str, chunk_size: usize) -> String {
    const MARKER: &str = "|i| {";
    let Some(rel) = text.find(MARKER) else {
        return text.to_string();
    };
    let brace_abs = rel + MARKER.len() - 1;
    let inner_start = brace_abs + 1;
    let Some(close_rel) = find_matching_close(&text[inner_start..]) else {
        // Malformed (shouldn't happen for real printer output) -- leave
        // the rest untouched rather than risk corrupting it.
        return text.to_string();
    };
    let inner_end = inner_start + close_rel;
    let mut out = String::with_capacity(text.len());
    out.push_str(&text[..inner_start]);
    out.push_str(&chunk_one_body(&text[inner_start..inner_end], chunk_size));
    out.push('}');
    // Keep scanning the remainder for any further closures (a function
    // can have many wide `Poly` statements, each its own closure).
    out.push_str(&chunk_closures_in_text(&text[inner_end + 1..], chunk_size));
    out
}

/// Chunk one function's own body text (already unwrapped of its own
/// outer `{`/`}`) into nested blocks of at most `chunk_size` top-level
/// statements each. Returns the transformed body text (still without
/// its own outer `{`/`}` -- the caller re-adds those). Also recurses
/// into any closure bodies found anywhere within (see
/// [`chunk_closures_in_text`]) -- independently of whether the outer
/// body itself needs chunking, since a closure can be large even when
/// its enclosing function isn't.
fn chunk_one_body(body: &str, chunk_size: usize) -> String {
    let body = chunk_closures_in_text(body, chunk_size);
    let (stmts, tail) = split_top_level(&body);
    if stmts.len() <= chunk_size {
        return body;
    }

    let ends = chunk_end_indices(&stmts, chunk_size);
    let mut chunks: Vec<&[&str]> = Vec::with_capacity(ends.len() + 1);
    let mut start = 0usize;
    for &end in &ends {
        chunks.push(&stmts[start..end]);
        start = end;
    }
    chunks.push(&stmts[start..]);
    let n = chunks.len();
    let mut used_after: BTreeSet<String> = extract_identifiers(tail);
    let mut rendered: Vec<String> = alloc::vec![String::new(); n];

    for idx in (0..n).rev() {
        let chunk = chunks[idx];

        let mut defined_order: Vec<String> = Vec::new();
        let mut defined_set: BTreeSet<String> = BTreeSet::new();
        let mut defined_more_than_once: BTreeSet<String> = BTreeSet::new();
        for s in chunk {
            for name in extract_let_bound_names(s) {
                if defined_set.insert(name.clone()) {
                    defined_order.push(name);
                } else {
                    defined_more_than_once.insert(name);
                }
            }
        }
        // A name `let`-(re)defined more than once *within this one
        // chunk* is a shadowed/reused scratch temp (this pipeline's own
        // generated code never gives a genuine, individually-meaningful
        // value more than one `let` for the same name in one function --
        // every real circuit value gets a unique name) -- never a
        // candidate for cross-chunk export, regardless of what
        // `used_after` says, since its last-defined instance may already
        // be consumed (e.g. moved into a `_pool.push(...)`) by the time
        // this chunk's own trailing export tuple would try to read it
        // again -- this text-level pass has no way to prove otherwise.
        let exports: Vec<String> = defined_order
            .into_iter()
            .filter(|nm| !defined_more_than_once.contains(nm) && used_after.contains(nm))
            .collect();

        let mut block = String::new();
        for s in chunk {
            block.push_str(s.trim());
            block.push('\n');
        }

        rendered[idx] = if exports.is_empty() {
            // Nothing crosses the boundary -- still isolate the chunk
            // into its own scope (bounding its rib) as a bare block
            // statement, no destructuring needed.
            format!("{{\n{block}}}\n")
        } else {
            let tuple_pat = exports.iter().map(|e| format!("mut {e}")).collect::<Vec<_>>().join(", ");
            let tuple_ret = exports.iter().map(|e| format!("{e}.clone()")).collect::<Vec<_>>().join(", ");
            if exports.len() == 1 {
                block.push_str(&tuple_ret);
                block.push('\n');
                format!("let {tuple_pat} = {{\n{block}}};\n")
            } else {
                block.push_str(&format!("({tuple_ret})\n"));
                format!("let ({tuple_pat}) = {{\n{block}}};\n")
            }
        };

        for s in chunk {
            used_after.extend(extract_referenced_identifiers(s));
        }
        // A name this chunk itself `let`-defines marks a shadowing
        // boundary: anything *before* this chunk (further "backward",
        // i.e. processed in later loop iterations) that shares the name
        // refers to a *different* binding, not this one -- so once this
        // chunk's own exports/references have been resolved against the
        // current `used_after`, remove its own defined names from it.
        // Removing *after* adding this chunk's own references (not
        // before) matters: a chunk can both define and reference the
        // same fixed/reused name internally (e.g. `let _tmp = f();
        // pool.push(_tmp);`), and that self-reference must not leak past
        // this chunk's own boundary as if it were a genuine external
        // need.
        for name in &defined_set {
            used_after.remove(name);
        }
    }

    let mut out = String::with_capacity(body.len() + n * 32);
    for r in rendered {
        out.push_str(&r);
    }
    if !tail.is_empty() {
        out.push_str(tail);
        out.push('\n');
    }
    out
}

#[cfg(test)]
mod tests {
    extern crate std;
    use super::*;

    #[test]
    fn body_under_threshold_is_unchanged() {
        let src = "fn f() {\nlet a = 1;\nlet b = 2;\n(a, b)\n}\n";
        assert_eq!(chunk_function_bodies(src, 10), src);
    }

    #[test]
    fn body_over_threshold_gets_chunked_and_stays_balanced() {
        let mut body = String::new();
        for i in 0..10 {
            body += &format!("let v{i} = f(v{});\n", if i == 0 { 0 } else { i - 1 });
        }
        body += "(v9)\n";
        let src = format!("pub fn f() {{\n{body}}}\n");
        let out = chunk_function_bodies(&src, 3);
        assert_ne!(out, src, "an over-threshold body must actually be rewritten");
        // Every original binding name must still appear somewhere.
        for i in 0..10 {
            assert!(out.contains(&format!("v{i}")), "v{i} must survive chunking");
        }
        // Braces/parens must stay balanced (a crude but meaningful sanity
        // check that the rewrite didn't corrupt the structure).
        let mut depth = 0i32;
        for b in out.bytes() {
            match b {
                b'{' | b'(' | b'[' => depth += 1,
                b'}' | b')' | b']' => depth -= 1,
                _ => {}
            }
        }
        assert_eq!(depth, 0, "brackets must balance: {out}");
    }

    #[test]
    fn cross_chunk_reference_is_exported_and_reused() {
        // v0 is defined in the first chunk and used again in the last --
        // it must appear in some exported tuple, not just its own def.
        let src = "pub fn f() {\nlet v0 = a();\nlet v1 = b();\nlet v2 = c();\nlet v3 = d();\nlet v4 = e(v0);\n(v4)\n}\n";
        let out = chunk_function_bodies(src, 2);
        assert!(out.contains("v0.clone()"), "v0 must be exported via clone across the chunk boundary:\n{out}");
    }

    #[test]
    fn reused_shadowed_name_is_not_treated_as_a_later_reference() {
        // `_tmp` is a *fixed, reused* name (like the pool-scratch helpers'
        // own temp bindings: define, immediately move into `pool.push`,
        // repeat) -- every later `let _tmp = ...;` shadows the earlier
        // one, it doesn't reference it. `chunk_size=6` puts the first two
        // `_tmp` define+push pairs in one chunk (a real, load-bearing
        // repro: `_tmp` defined *twice within one chunk*, each instance
        // immediately moved -- the shape that broke the naive fix, where
        // a chunk's own trailing export tuple tried to `.clone()` an
        // already-moved `_tmp`), and the third pair alone in the next.
        let src = "pub fn f() {\n\
                    let _tmp = a();\n\
                    _pool.push(_tmp);\n\
                    let v1 = _pool[0].clone();\n\
                    let _tmp = b();\n\
                    _pool.push(_tmp);\n\
                    let v2 = _pool[1].clone();\n\
                    let _tmp = c();\n\
                    _pool.push(_tmp);\n\
                    let v3 = _pool[2].clone();\n\
                    (v1, v2, v3)\n\
                    }\n";
        let out = chunk_function_bodies(src, 6);
        assert!(
            !out.contains("_tmp.clone()"),
            "a fixed/reused name must never be exported -- including via its own chunk's trailing tuple, when it was defined more than once (each instance already moved) within that same chunk:\n{out}"
        );
    }

    #[test]
    fn chunk_boundary_never_splits_a_non_adjacent_define_and_use() {
        // Mirrors `vole.rs::emit_and`'s real QSim-role shape exactly:
        // `_and_wire`'s own definition (`let _and_wire = _and_qand.clone();`)
        // is *not* immediately followed by its own use -- an unrelated
        // `_pool.push(_and_qand);` sits in between. `chunk_size=2` puts a
        // "natural" boundary right in the middle of this 4-statement group
        // on every repetition, which is exactly the shape that broke the
        // earlier "only check the very next statement" boundary fix.
        let mut body = String::new();
        for _ in 0..3 {
            body += "let _and_qand = f();\n\
                     let _and_wire = _and_qand.clone();\n\
                     _pool.push(_and_qand);\n\
                     _pool.push(_and_wire);\n";
        }
        let src = format!("pub fn f() {{\n{body}(0)\n}}\n");
        let out = chunk_function_bodies(&src, 2);
        // Every `_and_wire`/`_and_qand` reference must still resolve
        // against a same-chunk (or, failing that, exported) binding --
        // the cheapest real check available without a real rustc
        // invocation is that brackets stay balanced and every push still
        // has a matching, non-exported-away definition in the same
        // block. Concretely: no chunk boundary marker (`};\nlet` or a
        // bare `{` opening a fresh block) may appear strictly between a
        // `let _and_wire = ..` and its own `_pool.push(_and_wire)`.
        for (i, _) in out.match_indices("let _and_wire = _and_qand.clone();") {
            let after = &out[i..];
            let push_pos = after.find("_pool.push(_and_wire)").expect("push must still exist");
            let between = &after[..push_pos];
            assert!(
                !between.contains("};") && between.matches('{').count() <= 1,
                "a chunk boundary split _and_wire's own definition from its use:\n{out}"
            );
        }
    }

    #[test]
    fn tuple_let_pattern_names_are_extracted() {
        let names = extract_let_bound_names("let (a, mut b, c) = f();");
        assert_eq!(names, alloc::vec!["a".to_string(), "b".to_string(), "c".to_string()]);
    }

    #[test]
    fn array_repeat_type_semicolon_is_not_a_statement_boundary() {
        let body = "let x: [u8; 5] = [0; 5];\nlet y = 1;\n(x, y)\n";
        let (stmts, tail) = split_top_level(body);
        assert_eq!(stmts.len(), 2, "the `;` inside `[u8; 5]`/`[0; 5]` must not split a statement: {stmts:?}");
        assert_eq!(tail, "(x, y)");
    }

    #[test]
    fn large_closure_body_gets_chunked_even_when_outer_function_does_not() {
        // Mirrors `emit_poly_wide`'s real shape: a short OUTER function
        // (well under `chunk_size`) whose entire body is one statement
        // wrapping a `core::array::from_fn(|i| { .. })` closure with an
        // OVER-threshold statement count of its own. `split_top_level`
        // treats the whole closure as one opaque top-level statement, so
        // without recursing into it, the closure's own rib would never
        // get bounded regardless of `chunk_size`.
        let mut inner = String::new();
        for i in 0..10 {
            inner += &format!("let x{i} = f(x{});\n", if i == 0 { 0 } else { i - 1 });
        }
        inner += "x9\n";
        let src = format!(
            "pub fn f() -> [u8; 4] {{\nlet r = core::array::from_fn(|i| {{\n{inner}}});\nr\n}}\n"
        );
        let outer_stmt_count = 2; // `let r = ..;` and the trailing `r`
        assert!(outer_stmt_count <= 3, "sanity: outer body itself must be under threshold");
        let out = chunk_function_bodies(&src, 3);
        assert_ne!(out, src, "the closure body must be rewritten even though the outer function isn't");
        for i in 0..10 {
            assert!(out.contains(&format!("x{i}")), "x{i} must survive closure-body chunking:\n{out}");
        }
        // The closure's own body must actually have been split into more
        // than one nested block -- i.e. more `{` than just its own
        // single opening brace between "|i| {" and the closure's own
        // matching close.
        let closure_start = out.find("|i| {").expect("closure marker must survive:\n{out}");
        let inner_open = closure_start + "|i| {".len() - 1;
        let close_rel = find_matching_close(&out[inner_open + 1..]).expect("closure must stay brace-balanced");
        let closure_body = &out[inner_open + 1..inner_open + 1 + close_rel];
        assert!(
            closure_body.matches('{').count() >= 1,
            "closure body must contain at least one nested chunk block of its own:\n{out}"
        );
        // Overall brace/paren/bracket balance, same sanity check as the
        // outer-only chunking test above.
        let mut depth = 0i32;
        for b in out.bytes() {
            match b {
                b'{' | b'(' | b'[' => depth += 1,
                b'}' | b')' | b']' => depth -= 1,
                _ => {}
            }
        }
        assert_eq!(depth, 0, "brackets must balance: {out}");
    }
}
